require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TypeAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # TypeAddress. As you add validations to TypeAddress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TypeAddressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all type_addresses as @type_addresses" do
      type_address = TypeAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:type_addresses).should eq([type_address])
    end
  end

  describe "GET show" do
    it "assigns the requested type_address as @type_address" do
      type_address = TypeAddress.create! valid_attributes
      get :show, {:id => type_address.to_param}, valid_session
      assigns(:type_address).should eq(type_address)
    end
  end

  describe "GET new" do
    it "assigns a new type_address as @type_address" do
      get :new, {}, valid_session
      assigns(:type_address).should be_a_new(TypeAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested type_address as @type_address" do
      type_address = TypeAddress.create! valid_attributes
      get :edit, {:id => type_address.to_param}, valid_session
      assigns(:type_address).should eq(type_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TypeAddress" do
        expect {
          post :create, {:type_address => valid_attributes}, valid_session
        }.to change(TypeAddress, :count).by(1)
      end

      it "assigns a newly created type_address as @type_address" do
        post :create, {:type_address => valid_attributes}, valid_session
        assigns(:type_address).should be_a(TypeAddress)
        assigns(:type_address).should be_persisted
      end

      it "redirects to the created type_address" do
        post :create, {:type_address => valid_attributes}, valid_session
        response.should redirect_to(TypeAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved type_address as @type_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        TypeAddress.any_instance.stub(:save).and_return(false)
        post :create, {:type_address => { "description" => "invalid value" }}, valid_session
        assigns(:type_address).should be_a_new(TypeAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TypeAddress.any_instance.stub(:save).and_return(false)
        post :create, {:type_address => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested type_address" do
        type_address = TypeAddress.create! valid_attributes
        # Assuming there are no other type_addresses in the database, this
        # specifies that the TypeAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TypeAddress.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => type_address.to_param, :type_address => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested type_address as @type_address" do
        type_address = TypeAddress.create! valid_attributes
        put :update, {:id => type_address.to_param, :type_address => valid_attributes}, valid_session
        assigns(:type_address).should eq(type_address)
      end

      it "redirects to the type_address" do
        type_address = TypeAddress.create! valid_attributes
        put :update, {:id => type_address.to_param, :type_address => valid_attributes}, valid_session
        response.should redirect_to(type_address)
      end
    end

    describe "with invalid params" do
      it "assigns the type_address as @type_address" do
        type_address = TypeAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TypeAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => type_address.to_param, :type_address => { "description" => "invalid value" }}, valid_session
        assigns(:type_address).should eq(type_address)
      end

      it "re-renders the 'edit' template" do
        type_address = TypeAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TypeAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => type_address.to_param, :type_address => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested type_address" do
      type_address = TypeAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => type_address.to_param}, valid_session
      }.to change(TypeAddress, :count).by(-1)
    end

    it "redirects to the type_addresses list" do
      type_address = TypeAddress.create! valid_attributes
      delete :destroy, {:id => type_address.to_param}, valid_session
      response.should redirect_to(type_addresses_url)
    end
  end

end
